// react-example/src/App.tsx
import "./App.css";
import { Products } from "./Products";
import { Select } from "./Select";
import { SelectData, useFilters } from "./useFilters";

function App() {
  const { controls, filteredProducts, query } = useFilters();
  return (
    <div>
      {controls.map((ctrl) => {
        switch (ctrl.type()) {
          case "select":
            const selectData: SelectData = ctrl.data();
            return (
              <Select
                label={selectData.label}
                options={selectData.options}
                onChange={(value) => ctrl.filter().setValue(value)}
              />
            );

          default:
            return null;
        }
      })}
      <pre>q: {query.string()}</pre>
      <hr />
      <pre>payload: {JSON.stringify(query.object())}</pre>
      <Products products={filteredProducts} />
    </div>
  );
}

export default App;

// vue-example/src/App.vue
<script setup lang="ts">
import Products from './components/Products.vue'
import Select from './components/Select.vue'
import useFilters from './composables/useFilters'
const { products, controls, filteredProducts, queryString, payload } = useFilters();
</script>

<template>
  <template v-for="c of controls">
    <Select v-if="c.type() === 'select'" :data="c.data()" @select="c.filter().setValue($event)"
      :value="c.filter().value().value().toString()" />
  </template>
  <pre>queryString: {{ queryString }}</pre>
  <hr>
  <pre>payload: {{ payload }}</pre>
  <Products :products="filteredProducts" />
</template>
