// vue-example/src/App.vue
<script setup lang="ts">
import Products from './components/Products.vue'
import Select from './components/Select.vue'
import useFilters from './composables/useFilters'
const { products, controls, filteredProducts, queryString, payload } = useFilters();
</script>

<template>
  <template v-for="c of controls">
    <Select v-if="c.type() === 'select'" :data="c.data()" @select="c.filter().setValue($event)"
      :value="c.filter().value().value().toString()" />
  </template>
  <pre>queryString: {{ queryString }}</pre>
  <hr>
  <pre>payload: {{ payload }}</pre>
  <Products :products="filteredProducts" />
</template>

// svelte-example/src/App.svelte
<script lang="ts">
  import { filters } from "./features/filters";
  let { products, controls, filteredProducts, queryString, payload } =
    filters();
  import Products from "./components/Products.svelte";
  import Select from "./components/Select.svelte";
</script>

<main>
  {#each $controls as c}
    {#if c.type() === "select"}
      <Select
        data={c.data()}
        on:change={(e) => c.filter().setValue(e.detail)}
      />
    {/if}
  {/each}
  <pre>queryString: {$queryString}</pre>
  <pre>payload: {$payload}</pre>
  <Products products={$filteredProducts} />
</main>
