// react-example/src/Products.tsx
import { products } from "./data";

export type Product = (typeof products)[0];

interface Props {
  products: Product[];
}
export const Products = (props: Props) => {
  return (
    <ul>
      {props.products.map((p) => (
        <li key={p.emoji} className="product">
          <h2>{p.emoji}</h2>
          <small>{p.category}</small>
          <hr />
          <span className="price">💵 {p.price}</span>
        </li>
      ))}
    </ul>
  );
};

// angular-example/src/app/components/products/products.component.ts
import { Component, Input } from '@angular/core';
import { Product } from 'src/app/data';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.css'],
})
export class ProductsComponent {
  @Input() products: Product[] = [];
}

<ul>
  <li *ngFor="let product of products" class="product">
    <h2>{{ product.emoji }}</h2>
    <small>{{ product.category }}</small>
    <hr />
    <span className="price">💵 {{ product.price }}</span>
  </li>
</ul>
