// vue-example/src/components/Select.vue
<script setup lang="ts">

const props = defineProps<{
  value: string;
  data: {
    label: string;
    options: string[];
  }
}>()

const emit = defineEmits<{
  (e: 'select', value: string): void
}>()

function onChange(e: Event) {
  const target = e.target as HTMLSelectElement
  emit('select', target.value)
}

</script>

<template>
  <select class="select" @change="onChange($event)">
    <option value="">{{ props.data.label }}</option>;
    <option v-for="opt of props.data.options" :value="opt">
      {{ opt }}
    </option>
  </select>
</template>

// react-example/src/Select.tsx
interface Props {
  options: string[];
  label: string;
  onChange: (value: string) => void;
}

export const Select = (props: Props) => {
  return (
    <select className="select" onChange={(e) => props.onChange(e.target.value)}>
      <option value="">{props.label}</option>;
      {props.options.map((opt) => {
        return (
          <option key={opt} value={opt}>
            {opt}
          </option>
        );
      })}
    </select>
  );
};
