// react-example/src/Products.tsx
import { products } from "./data";

export type Product = (typeof products)[0];

interface Props {
  products: Product[];
}
export const Products = (props: Props) => {
  return (
    <ul>
      {props.products.map((p) => (
        <li key={p.emoji} className="product">
          <h2>{p.emoji}</h2>
          <small>{p.category}</small>
          <hr />
          <span className="price">💵 {p.price}</span>
        </li>
      ))}
    </ul>
  );
};

// vue-example/src/components/Products.vue
<script setup lang="ts">
import Product from "../composables/useFilters"
defineProps<{ products: Product[] }>()
</script>

<template>
  <ul>
    <li v-for="p of products" key={p.emoji} class="product">
      <h2>{{ p.emoji }}</h2>
      <small>{{ p.category }}</small>
      <hr />
      <span class="price">💵 {{ p.price }}</span>
    </li>
  </ul>
</template>
