// svelte-example/src/components/Select.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type { SelectData } from "../features/filters";

  export let data: SelectData;

  const dispatch = createEventDispatcher();

  function onChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    dispatch("change", target.value);
  }
</script>

<select class="select" on:change={onChange}>
  <option value="">{data.label}</option>;
  {#each data.options as opt}
    <option value={opt}>
      {opt}
    </option>
  {/each}
</select>

// vue-example/src/components/Select.vue
<script setup lang="ts">

const props = defineProps<{
  value: string;
  data: {
    label: string;
    options: string[];
  }
}>()

const emit = defineEmits<{
  (e: 'select', value: string): void
}>()

function onChange(e: Event) {
  const target = e.target as HTMLSelectElement
  emit('select', target.value)
}

</script>

<template>
  <select class="select" @change="onChange($event)">
    <option value="">{{ props.data.label }}</option>;
    <option v-for="opt of props.data.options" :value="opt">
      {{ opt }}
    </option>
  </select>
</template>
