// vue-example/src/App.vue
<script setup lang="ts">
import Products from './components/Products.vue'
import Select from './components/Select.vue'
import useFilters from './composables/useFilters'
const { products, controls, filteredProducts, queryString, payload } = useFilters();
</script>

<template>
  <template v-for="c of controls">
    <Select v-if="c.type() === 'select'" :data="c.data()" @select="c.filter().setValue($event)"
      :value="c.filter().value().value().toString()" />
  </template>
  <pre>queryString: {{ queryString }}</pre>
  <hr>
  <pre>payload: {{ payload }}</pre>
  <Products :products="filteredProducts" />
</template>

// angular-example/src/app/app.component.ts
import { Component } from '@angular/core';
import { ProductsService } from './services/products.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-example';

  constructor(public readonly productsService: ProductsService) {}
}

<ng-container *ngFor="let c of productsService.controls">
    <ng-container [ngSwitch]="c.type()">
        <app-select (select)="c.filter().setValue($event)" [data]="c.data()" *ngSwitchCase="'select'"></app-select>
    </ng-container>
</ng-container>
<pre>
    queryString: {{ productsService.queryString }}
</pre>
<pre>
    payload: {{ productsService.payload }}
</pre>
<app-products [products]="productsService.products"></app-products>
