// vue-example/src/components/Select.vue
<script setup lang="ts">

const props = defineProps<{
  value: string;
  data: {
    label: string;
    options: string[];
  }
}>()

const emit = defineEmits<{
  (e: 'select', value: string): void
}>()

function onChange(e: Event) {
  const target = e.target as HTMLSelectElement
  emit('select', target.value)
}

</script>

<template>
  <select class="select" @change="onChange($event)">
    <option value="">{{ props.data.label }}</option>;
    <option v-for="opt of props.data.options" :value="opt">
      {{ opt }}
    </option>
  </select>
</template>

// angular-example/src/app/components/select/select.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

type SelectInput = {
  label: string;
  options: string[];
};

@Component({
  selector: 'app-select',
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.css'],
})
export class SelectComponent<T> {
  @Input() data: SelectInput = {
    label: '',
    options: [],
  };

  @Output() select = new EventEmitter<string>();
  @Input() value: string = '';

  onSelect(e: Event) {
    const target = e.target as HTMLSelectElement;
    this.select.emit(target.value);
  }
}

<select [value]="value" class="select" (change)="onSelect($event)">
  <option value="">{{ data.label }}</option>
  <option *ngFor="let option of data.options" value="{{ option}}">
    {{ option}}
  </option>
</select>
